CREATE SCHEMA IF NOT EXISTS coffework;

CREATE TABLE coffework.establishment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    adress VARCHAR(255),
    municipality VARCHAR(255),
    uf VARCHAR(2),
    description TEXT,
    assessment INTEGER,
    lng DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    CONSTRAINT chk_establishment_assessment
        CHECK (assessment IS NULL OR assessment BETWEEN 0 AND 5)
);

CREATE TABLE coffework.role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE coffework."user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE coffework.users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user
        FOREIGN KEY (user_id)
        REFERENCES coffework."user" (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role
        FOREIGN KEY (role_id)
        REFERENCES coffework.role (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_establishment_name ON coffework.establishment (name);
CREATE INDEX idx_establishment_assessment ON coffework.establishment (assessment);
CREATE INDEX idx_establishment_coordinates ON coffework.establishment (lat, lng);
CREATE INDEX idx_users_roles_role_id ON coffework.users_roles (role_id);
